import { MigrateOptions } from "fireway";

const sports = [
  { key: "3x3-basketball", label: "3x3 Basketball" },
  { key: "alpine-skiing", label: "Alpine Skiing" },
  { key: "american-football", label: "American Football" },
  { key: "archery", label: "Archery" },
  { key: "arm-wrestling", label: "Arm Wrestling" },
  { key: "armored-combat-sports", label: "Armored Combat Sports" },
  { key: "athletics-track-and-field", label: "Athletics (Track and Field)" },
  { key: "australian-football", label: "Australian Football" },
  { key: "badminton", label: "Badminton" },
  { key: "base-jumping", label: "Base Jumping" },
  { key: "baseball", label: "Baseball" },
  { key: "basketball", label: "Basketball" },
  { key: "beach-soccer", label: "Beach Soccer" },
  { key: "biathlon", label: "Biathlon" },
  { key: "bmx-racing", label: "BMX Racing" },
  { key: "bobsleigh", label: "Bobsleigh" },
  { key: "boccia", label: "Boccia" },
  { key: "bodybuilding", label: "Bodybuilding" },
  { key: "bossaball", label: "Bossaball" },
  { key: "bowling", label: "Bowling" },
  { key: "boxing", label: "Boxing" },
  { key: "brazilian-jiu-jitsu", label: "Brazilian Jiu-Jitsu" },
  { key: "bullfighting", label: "Bullfighting" },
  { key: "calisthenics", label: "Calisthenics" },
  { key: "camel-racing", label: "Camel Racing" },
  {
    key: "canoe-kayak-slalom-and-sprint",
    label: "Canoe/Kayak (Slalom and Sprint)",
  },
  { key: "capoeira", label: "Capoeira" },
  { key: "cheerleading", label: "Cheerleading" },
  { key: "chess", label: "Chess" },
  { key: "climbing", label: "Climbing" },
  { key: "cricket", label: "Cricket" },
  { key: "cross-country-running", label: "Cross Country Running" },
  { key: "cross-country-skiing", label: "Cross Country Skiing" },
  { key: "crossfit", label: "Crossfit" },
  { key: "curling", label: "Curling" },
  { key: "cycling", label: "Cycling" },
  { key: "darts", label: "Darts" },
  { key: "decathlon", label: "Decathlon" },
  { key: "disc-golf", label: "Disc Golf" },
  { key: "diving", label: "Diving" },
  { key: "dodgeball", label: "Dodgeball" },
  { key: "dog-sledding", label: "Dog Sledding" },
  { key: "drag-racing", label: "Drag Racing" },
  { key: "dragon-boat-racing", label: "Dragon Boat Racing" },
  { key: "equestrian", label: "Equestrian" },
  { key: "esports", label: "eSports" },
  { key: "fencing", label: "Fencing" },
  { key: "field-hockey", label: "Field Hockey" },
  { key: "figure-skating", label: "Figure Skating" },
  { key: "fishing", label: "Fishing" },
  { key: "floorball", label: "Floorball" },
  {
    key: "flying-disc-ultimate-frisbee",
    label: "Flying Disc (Ultimate Frisbee)",
  },
  { key: "football-soccer", label: "Football (Soccer)" },
  { key: "freestyle-skiing", label: "Freestyle Skiing" },
  { key: "freestyle-wrestling", label: "Freestyle Wrestling" },
  { key: "futsal", label: "Futsal" },
  { key: "gaelic-football", label: "Gaelic Football" },
  { key: "goalball", label: "Goalball" },
  { key: "golf", label: "Golf" },
  { key: "greco-roman-wrestling", label: "Greco-Roman Wrestling" },
  { key: "greyhound-racing", label: "Greyhound Racing" },
  { key: "gymnastics", label: "Gymnastics" },
  { key: "handball", label: "Handball" },
  { key: "hang-gliding", label: "Hang Gliding" },
  { key: "highland-games", label: "Highland Games" },
  { key: "hiking", label: "Hiking" },
  { key: "horse-polo", label: "Horse Polo" },
  { key: "horse-racing", label: "Horse Racing" },
  { key: "hurling", label: "Hurling" },
  { key: "ice-hockey", label: "Ice Hockey" },
  { key: "ice-skating", label: "Ice Skating" },
  { key: "ice-sledge-hockey", label: "Ice Sledge Hockey" },
  { key: "indoor-soccer", label: "Indoor Soccer" },
  { key: "inline-hockey", label: "Inline Hockey" },
  { key: "jai-alai", label: "Jai Alai" },
  { key: "jet-skiing", label: "Jet Skiing" },
  { key: "judo", label: "Judo" },
  { key: "kabaddi", label: "Kabaddi" },
  { key: "karate", label: "Karate" },
  { key: "kayaking", label: "Kayaking" },
  { key: "kendo", label: "Kendo" },
  { key: "kite-surfing", label: "Kite Surfing" },
  { key: "kiteboarding", label: "Kiteboarding" },
  { key: "korfball", label: "Korfball" },
  { key: "lacrosse", label: "Lacrosse" },
  { key: "luge", label: "Luge" },
  { key: "martial-arts", label: "Martial Arts" },
  { key: "mma-mixed-martial-arts", label: "MMA (Mixed Martial Arts)" },
  { key: "modern-pentathlon", label: "Modern Pentathlon" },
  { key: "monster-truck-racing", label: "Monster Truck Racing" },
  { key: "motocross", label: "Motocross" },
  { key: "motor-sports-racing", label: "Motor Sports Racing" },
  { key: "mountain-biking", label: "Mountain Biking" },
  { key: "mountaineering", label: "Mountaineering" },
  { key: "muay-thai", label: "Muay Thai" },
  { key: "netball", label: "Netball" },
  { key: "nordic-combined", label: "Nordic Combined" },
  { key: "obstacle-course-racing", label: "Obstacle Course Racing" },
  { key: "orienteering", label: "Orienteering" },
  { key: "paddle-tennis", label: "Paddle Tennis" },
  { key: "paddleboarding", label: "Paddleboarding" },
  { key: "paragliding", label: "Paragliding" },
  { key: "parasailing", label: "Parasailing" },
  { key: "parkour", label: "Parkour" },
  { key: "pickleball", label: "Pickleball" },
  { key: "power-boating", label: "Power Boating" },
  { key: "powerlifting", label: "Powerlifting" },
  { key: "racquetball", label: "Racquetball" },
  { key: "rafting", label: "Rafting" },
  { key: "rally-racing", label: "Rally Racing" },
  { key: "rhythmic-gymnastics", label: "Rhythmic Gymnastics" },
  { key: "ringette", label: "Ringette" },
  { key: "rock-climbing", label: "Rock Climbing" },
  { key: "roller-derby", label: "Roller Derby" },
  { key: "roller-skating", label: "Roller Skating" },
  {
    key: "roller-skating-and-roller-derby",
    label: "Roller Skating and Roller Derby",
  },
  { key: "rowing", label: "Rowing" },
  { key: "rugby", label: "Rugby" },
  { key: "running", label: "Running" },
  { key: "sailing", label: "Sailing" },
  { key: "scuba-diving", label: "Scuba Diving" },
  { key: "sepak-takraw", label: "Sepak Takraw" },
  { key: "shooting", label: "Shooting" },
  { key: "short-track-speed-skating", label: "Short Track Speed Skating" },
  { key: "sitting-volleyball", label: "Sitting Volleyball" },
  { key: "skateboarding", label: "Skateboarding" },
  { key: "skeleton", label: "Skeleton" },
  { key: "ski-jumping", label: "Ski Jumping" },
  { key: "skiing", label: "Skiing" },
  { key: "skydiving", label: "Skydiving" },
  { key: "snooker", label: "Snooker" },
  { key: "snowboarding", label: "Snowboarding" },
  { key: "snowmobiling", label: "Snowmobiling" },
  { key: "softball", label: "Softball" },
  { key: "speed-skating", label: "Speed Skating" },
  { key: "sport-climbing", label: "Sport Climbing" },
  { key: "squash", label: "Squash" },
  { key: "stunt-riding", label: "Stunt Riding" },
  { key: "sumo-wrestling", label: "Sumo Wrestling" },
  { key: "surfing", label: "Surfing" },
  { key: "swimming", label: "Swimming" },
  { key: "synchronized-swimming", label: "Synchronized Swimming" },
  { key: "table-tennis", label: "Table Tennis" },
  { key: "taekwondo", label: "Taekwondo" },
  { key: "tennis", label: "Tennis" },
  { key: "throwball", label: "Throwball" },
  { key: "trampoline-gymnastics", label: "Trampoline Gymnastics" },
  { key: "triathlon", label: "Triathlon" },
  { key: "tug-of-war", label: "Tug of War" },
  { key: "ultramarathon", label: "Ultramarathon" },
  { key: "underwater-hockey", label: "Underwater Hockey" },
  { key: "volleyball", label: "Volleyball" },
  { key: "wakeboarding", label: "Wakeboarding" },
  { key: "walking", label: "Walking" },
  { key: "water-polo", label: "Water Polo" },
  { key: "weightlifting", label: "Weightlifting" },
  { key: "wheelchair-basketball", label: "Wheelchair Basketball" },
  { key: "wheelchair-rugby", label: "Wheelchair Rugby" },
  { key: "wheelchair-tennis", label: "Wheelchair Tennis" },
  { key: "windsurfing", label: "Windsurfing" },
  { key: "wrestling", label: "Wrestling" },
  { key: "wushu", label: "Wushu" },
  { key: "yoga", label: "Yoga" },
];

export async function migrate({ firestore }: MigrateOptions) {
  await firestore.collection("public").doc("sports").set({ all: sports });
}
