name: Deploy Dev

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install -g firebase-tools yarn

      - name: Lint project
        run: yarn lint

      - name: Deploy to Firebase
        run: firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }} --project heros-dev-386505

